### PR TITLE
S3 plugin update

### PR DESCRIPTION
**Pull request by longlho**
Hi Richard, 

First of all thanks a lot for contributing to this plugin. I actually used it a lot both at home and at work. I've made some changes to it and hopefully they can be incorporated in the master branch. The main changes are:
- Switch from jets3 to amazonaws library since it's officially supported by Amazon. The library has a lil bit of a learning curve to it but once u get used to it it's actually pretty good.
- Fix concurrency problem when multiple jobs are uploading the artifacts at the same time.
- Added unit test (so far only 1 but I'm working on it).

Let me know what you thinks. I'm looking forward to your feedback. Hopefully if u don't mind this can be incorporate into the Jenkins main plugin repository.

Thanks a lot,

Long Ho

### CODE REVIEW

**Comment by d6y** [comment]
Hi - and thank you.  Just wanted to let you know I'l try to get to review
this today, but if I can't it probably won't be until Thursday or Friday
this week.

**Comment by longlho** [comment]
Sure thanks a lot!! I wrote this patch actually based on an older master from doug so the main changes only are the aws driver, the concurrency and unit test which I'll continue to develop. I want to add some features to this plugin like comma-separated buckets and dynamic defined properties as well.

**Comment by d6y** [comment]
I've not forgotten about this.  This week.  Definitely this week.

**Comment by longlho** [comment]
Lol take your time! Thanks!

**Comment by d6y** [comment]
Working on merging now.  There are some conflicts to work through (oddly).  

BTW, this project now lives at https://github.com/jenkinsci/s3-plugin

**Comment by d6y** [comment]
Right - I think I see what the issue is here.  This pull request is against Doug's last set of changes, whereas this fork has moved on quite a bit since then.  That's what it looks like from the graph here: https://github.com/d6y/hudson-s3/network

Is there any chance you could either: rebase or merge against the lasted of https://github.com/d6y/hudson-s3 ?  Or even against the https://github.com/jenkinsci/s3-plugin fork?

**Comment by longlho** [comment]
Yup I can def work on that today.

**Comment by d6y** [comment]
Thank you for reworking this against s3-plugin. I'll close this request as it's now all happening over at https://github.com/jenkinsci/s3-plugin/pull/1

**Pull request closed without merging**
